#!/usr/bin/env bash
set -euo pipefail

echo "Claude Conductor - Installation"
echo ""
echo "This tool now requires Go to build from source."
echo ""
echo "Installation steps:"
echo ""
echo "  1. Clone the repository:"
echo "     git clone https://github.com/brittonhayes/claude-conductor"
echo "     cd claude-conductor"
echo ""
echo "  2. Build and install:"
echo "     make install"
echo ""
echo "Or build manually:"
echo "  go build -o conductor ./cmd/conductor"
echo "  mv conductor ~/.local/bin/"
echo ""
echo "Requirements:"
echo "  - Go 1.21+"
echo "  - Claude Code CLI (claude)"
echo ""
exit 0
